tasks:
  - before: |
      sudo apt-get update
      sudo apt-get install --assume-yes --no-install-recommends ffmpeg
    init: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --requirement requirements.txt
    command: |
      source .venv/bin/activate
      until python main.py; do sleep 1; done

ports:
  - port: 8000
    visibility: public

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
